### ISSUE TITLE
what are some unsupported methods?

### ISSUE THREAD

**Issue by ghost** [brandicted/scrapy-webdriver#1]
page screenshot?
navigation events?
executeScript()?

**Comment by ncadou** [comment]
Those are all supported, as you have access to a raw webdriver instance. What's not complete is the integration between scrapy and webdriver. So if you use the normal scrapy way of setting cookies for example, webdriver won't use that info.

**Comment by ghost** [comment]
is it possible to have them share cookies? What are the exact items missing for integration between scrapy and webdriver?

**Comment by ncadou** [comment]
Sure. There are ways to deal with cookies both in scrapy and webdriver, so it's possible to integrate them.
