### ISSUE TITLE
Broken compatibility with Scrapy <0.18

### ISSUE THREAD

**Issue by imiric** [brandicted/scrapy-webdriver#10]
Just to let you know that 9671684fccee080cb36522f9b2f64e1c7b6ff782 broke compatibility with Scrapy versions lower than 0.18. Using scrapy-webdriver on that changeset with Scrapy 0.16.5 throws the error:

```
ImportError: Error loading object 'scrapy.core.downloader.handlers.http10.HTTP10DownloadHandler': No module named http10
```

I have reverted to using 079ab6a6fadda4e34371d8165fbd1f0c3cc410c4 which works correctly.

You should probably specify in the README which Scrapy version scrapy-webdriver supports, although a fix for this should be straightforward.

Also, consider doing a version bump in these cases and uploading the package to PyPI would make things easier.

Thanks for your work!

**Comment by ncadou** [comment]
Thanks for your report!

While I have yet to find some time to upload scrapy-webdriver to PyPI, I believe that e9ce7b926a718787c466be74a38249e988d34d3d fixes this issue. Please let me know.

**Comment by imiric** [comment]
Indeed, that does it. Thanks for the quick fix!
